apiVersion: v1
kind: Pod
metadata:
  name: hello-world-cli
  namespace: defult
  labels:
    app: hello-world-cli
spec:
  imagePullSecrets:
  - name: gcr-io
  containers:
  - image: ko://github.com/GoTurkiye/hello-world-cli
    name: hello-world-cli
